### ISSUE TITLE
"The 'livestreamer' distribution was not found and is required by livestreamer-curses"

### ISSUE THREAD

**Issue by Hund** [RadicalEd360/Patches#1]
I just installed livestreamer-curses and copied the files to `/usr/lib/python3.6/site-packages/livestreamer_curses`. I'm on Arch and I have Python 3.6 (not 3.5). This is what happens when I try to run it:

```
Traceback (most recent call last):
  File "/usr/bin/livestreamer-curses", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'livestreamer' distribution was not found and is required by livestreamer-curses
```

**Comment by RadicalEd360** [comment]
which method are you installing livestreamer-curses?
using 'pip3 install livestreamer-curses' also installs livestreamer as well, are you removing it after install? does it work after you install livestreamer package or give error?

i havent used arch before so im curious.

looks like i need to patch poller.py as well, afterwards the program should not be trying to import it, afterwards i will check if its a dependancy to run it tho, if not livestreamer wont need to be installed at all, but atm it needs to be installed in order to check if streams are online, but everything else uses streamlink

**Comment by Hund** [comment]
I downloaded the pkgbuild from the package `livestreamer-curses`, removed the livestreamer dependency and installed it.

It works if I install livestreamer, but it seems like it's using that backend then.

**Comment by RadicalEd360** [comment]
alright i patched poller.py, if you put that in your directory it should work without livestreamer installed

**Comment by Hund** [comment]
```
# cp poller.py /usr/lib/python3.6/site-packages/livestreamer_curses/
$ livestreamer-curses
Traceback (most recent call last):
  File "/usr/bin/livestreamer-curses", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'livestreamer' distribution was not found and is required by livestreamer-curses
```

:)

**Comment by RadicalEd360** [comment]
at this point i wasnt sure so i just made this instead :)
https://github.com/RadicalEd360/streamlink-curses

**Comment by Hund** [comment]
That worked a lot better! :D Now I'm only missing a option to change the colors as they look weird for me. :)

![streamlink-curses](https://user-images.githubusercontent.com/320498/34340494-fa64de88-e984-11e7-82e9-369d570a55c9.png)
